-- Script de Configuração da Base de Dados - Área de Membros
-- Execute este script no SQL Editor do seu novo projeto Supabase

-- 1. Habilitar extensão para UUIDs (mantido por compatibilidade se necessário, mas não usado nas PKs agora)
create extension if not exists "uuid-ossp";

-- 2. Criar Tabela de Produtos
create table if not exists public.produtos (
    id bigint primary key generated by default as identity,
    name text not null,
    description text,
    se_bloqueado text, -- URL de redirecionamento se bloqueado
    cover_url text,
    ordem bigint default 0,
    created_at timestamp with time zone default now()
);

-- 3. Criar Tabela de Módulos
create table if not exists public.modules (
    id bigint primary key generated by default as identity,
    product_id bigint references public.produtos(id) on delete cascade,
    title text not null,
    description text,
    cover_url text,
    order_index bigint default 0,
    status text default 'publicado',
    created_at timestamp with time zone default now()
);

-- 4. Criar Tabela de Aulas (Lessons)
create table if not exists public.lessons (
    id bigint primary key generated by default as identity,
    module_id bigint references public.modules(id) on delete cascade,
    title text not null,
    description text,
    video_url text,
    attachment_url text,
    order_index bigint default 0,
    created_at timestamp with time zone default now()
);

-- 5. Criar Tabela de Compras (Controle de Acesso)
create table if not exists public.compras (
    id bigint primary key generated by default as identity,
    email text not null,
    nome_do_produto text,
    primeiro_nome text,
    nome_completo text,
    data text,
    horario text,
    created_at timestamp with time zone default now()
);

-- 6. Criar Tabela de Anexos
create table if not exists public.anexos (
    id bigint primary key generated by default as identity,
    modulo_id bigint references public.modules(id) on delete cascade,
    titulo text not null,
    arquivo_url text not null,
    ordem bigint default 0,
    created_at timestamp with time zone default now()
);

-- 7. Criar Tabela de Configurações do Site
create table if not exists public.site_settings (
    id bigint primary key generated by default as identity,
    hero_title text,
    hero_subtitle text,
    motivational_text text,
    updated_at timestamp with time zone default now()
);

-- 8. Inserir uma configuração inicial (opcional)
insert into public.site_settings (hero_title, hero_subtitle, motivational_text)
values ('Bem-vindo!', 'Sua jornada começa aqui.', 'Foco e persistência são a chave do sucesso.');

-- NOTA IMPORTANTE:
-- Por padrão, o RLS está desativado no seu projeto antigo (o que é inseguro).
-- Para este novo projeto, recomendo habilitar o RLS e criar políticas de acesso.
-- Se quiser apenas que funcione como o antigo (aberto), as tabelas já estão prontas.
